// Database types for Supabase

export type Role = 'employee' | 'manager';

export type RecordStatus = 'draft' | 'submitted' | 'approved' | 'rejected';

export interface User {
  id: string; // UUID (PK) — auto-generated by Supabase
  user_id: string; // 人間可読コード ('U001' etc.)
  name: string;
  password_hash: string;
  role: Role;
  is_active: boolean;
  created_at: string;
  qr_code?: string; // QRコードログイン用
}

export interface Product {
  id: string; // UUID (PK)
  product_code: string; // 'P001' etc.
  name: string;
  icon: string | null;
  sort_order: number;
  is_active: boolean;
}

export interface Line {
  id: string; // UUID (PK)
  line_code: string; // 'L001' etc.
  name: string;
  sort_order: number;
  is_active: boolean;
}

export interface Template {
  id: string; // UUID (PK) — Supabase actual column
  product_id: string;
  version: number;
  sections: Section[]; // Supabase actual column (not sections_json)
  created_at?: string;
  is_active: boolean;
}

export interface CheckRecord {
  id: string; // UUID (PK) — auto-generated by Supabase
  template_id: string;
  product_id: string;
  line_id: string; // UUID — references lines.id
  production_date: string;
  batch_number: number;
  status: RecordStatus;
  current_editor_id: string | null; // UUID — references users.id
  created_by: string; // UUID — references users.id
  created_at: string;
  submitted_by: string | null; // UUID
  submitted_at: string | null;
  approved_by: string | null; // UUID
  approved_at: string | null;
  rejected_by: string | null; // UUID
  rejected_at: string | null;
  reject_reason: string | null;
}

export interface RecordItem {
  id: string;
  record_id: string;
  section_id: string;
  item_id: string;
  row_index: number;
  value: string | null;
  input_by: string | null;
  input_at: string;
  updated_by: string | null;
  updated_at: string | null;
}

export interface ItemChangeLog {
  id: string;
  record_id: string;
  record_item_id: string | null;
  section_id: string;
  item_id: string;
  old_value: string | null;
  new_value: string | null;
  changed_by: string;
  changed_at: string;
  change_reason: string | null;
  change_type: 'create' | 'update';
}

export interface OperationLog {
  id: string; // UUID (PK) — auto-generated
  user_id: string; // UUID
  action: string;
  target_type: string;
  target_id: string | null; // UUID
  details: Record<string, unknown> | null;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

// Template structure types
export interface Section {
  id: string; // Supabase actual column (not section_id)
  name: string;
  description?: string;
  repeatable?: boolean;
  min_rows?: number;
  max_rows?: number;
  columns_layout?: 'horizontal_scroll';
  fixed_labels?: string[];
  items?: Item[];
}

export interface Item {
  id: string; // Supabase actual column (not item_id)
  label: string;
  type: ItemType;
  required?: boolean;
  unit?: string;
  hint?: string;
  labels?: {
    ok: string;
    ng: string;
  };
  options?: string[];
  allow_self?: boolean;
  allow_now_button?: boolean;
  validation?: ValidationRule;
}

export type ItemType =
  | 'text'
  | 'number'
  | 'date'
  | 'time'
  | 'ok_ng'
  | 'select'
  | 'user_select'
  | 'line_select';

export interface ValidationRule {
  type: 'min' | 'max' | 'range' | 'expiry_date' | 'equals' | 'pattern';
  value?: number;
  min?: number;
  max?: number;
  regex?: string;
  message: string;
}

// Extended types with joins
export interface CheckRecordWithDetails extends CheckRecord {
  product_name: string;
  line_name: string;
  created_by_name: string;
  current_editor_name?: string;
  submitted_by_name?: string;
  approved_by_name?: string;
  rejected_by_name?: string;
}

export interface ItemValue {
  value: string | null;
  is_valid: boolean;
  input_by: string | null;
  input_at: string;
}

// Supabase Database type definition
export interface Database {
  public: {
    Tables: {
      users: {
        Row: User;
        Insert: Omit<User, 'created_at'> & { created_at?: string };
        Update: Partial<User>;
        Relationships: [];
      };
      products: {
        Row: Product;
        Insert: Product;
        Update: Partial<Product>;
        Relationships: [];
      };
      lines: {
        Row: Line;
        Insert: Line;
        Update: Partial<Line>;
        Relationships: [];
      };
      templates: {
        Row: Template;
        Insert: Omit<Template, 'created_at'> & { created_at?: string };
        Update: Partial<Template>;
        Relationships: [];
      };
      check_records: {
        Row: CheckRecord;
        Insert: Omit<CheckRecord, 'id' | 'created_at'> & { id?: string; created_at?: string };
        Update: Partial<CheckRecord>;
        Relationships: [];
      };
      record_items: {
        Row: RecordItem;
        Insert: RecordItem;
        Update: Partial<RecordItem>;
        Relationships: [];
      };
      item_change_logs: {
        Row: ItemChangeLog;
        Insert: Omit<ItemChangeLog, 'changed_at'> & { changed_at?: string };
        Update: Partial<ItemChangeLog>;
        Relationships: [];
      };
      operation_logs: {
        Row: OperationLog;
        Insert: Omit<OperationLog, 'id' | 'created_at'> & { id?: string; created_at?: string };
        Update: Partial<OperationLog>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      role: Role;
      record_status: RecordStatus;
    };
  };
}
